config/routes.rb
Rails.application.routes.draw do
  resources :vouchers, only: [:show, :new, :create]
  resources :restaurants, only: [:index, :show]
  devise_for :users
  # root to: 'pages#home'
  root to: "restaurants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
require 'json'
require 'open-uri'

class Restaurant < ApplicationRecord
  has_one_attached :photo
  has_many :vouchers
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  after_create :retrieve_additional_info

  def retrieve_additional_info
    geocoder_search = Geocoder.search(self.address)
    geocoder_search = geocoder_search.first if geocoder_search.kind_of?(Array)

    place_id = geocoder_search.data["place_id"]
    google_data = google_data_scrape(place_id)
    self.google_place_id = place_id
    self.website = google_data["result"]["website"] || ""

    google_file = URI.open(google_photos(place_id, 1200)[0])
    self.photo.attach(io: google_file, filename: `#restaurant_#{id}.png`, content_type: 'image/png')
    save
  end

  def google_photos(place_id, size)
    photo_data = google_data_scrape(place_id)["result"]["photos"] || [{"photo_reference"=>"CmRaAAAATv-bQAsMow0UfgHyr96wEfEB6gkMAvaVQy8c61mNoyzIws24sWsdZXWWCiPOir7R434o5WrzEy73IBgqQqz2sGBJnRu_fKjl6uAVnflohAkvvLvdPD3t1wGsrUbbz9y1EhCdmNq5ks47G4vwRph_g-BVGhQXgiq_9Kg_JryKuquYQ12cakzCfQ"}]
    # Added a random photo data so it would work
    photo_data.map { |x| photo_reference_to_url(x["photo_reference"], size) }
  end

  def google_data_scrape(place_id)
    google_data_url = "https://maps.googleapis.com/maps/api/place/details/json?placeid=#{place_id}&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
    JSON.parse(open(google_data_url).read)
  end

  def photo_reference_to_url(photo_reference, size)
    "https://maps.googleapis.com/maps/api/place/photo?photoreference=#{photo_reference}&sensor=false&maxheight=#{size}&maxwidth=#{size}&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
  end

  def tidy_address
    address.split(",")[1, 5].join(",")
  end

  def plural_vouchers
    vouchers.count > 1 ? "s" : ""
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vouchers
end

app/models/voucher.rb
require 'open-uri'

class Voucher < ApplicationRecord
  has_one_attached :photo
  belongs_to :restaurant
  after_create :image_from_google

  def image_from_google
    restaurant = self.restaurant
    google_file = URI.open(restaurant.google_photos(restaurant.google_place_id, 400).sample)
    self.photo.attach(io: google_file, filename: `#voucher_#{id}.png`, content_type: 'image/png')
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :latitude, :longitude, :city, :neighbourhood, :address, :website)
    end
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_voucher, only: [:show, :edit, :update, :destroy]

  # GET /vouchers
  # GET /vouchers.json
  def index
    @vouchers = Voucher.all
  end

  # GET /vouchers/1
  # GET /vouchers/1.json
  def show
  end

  # GET /vouchers/new
  def new
    @voucher = Voucher.new
  end

  # GET /vouchers/1/edit
  def edit
  end

  # POST /vouchers
  # POST /vouchers.json
  def create
    restaurant = Restaurant.find_by(address: params["voucher"][:restaurant])
    restaurant = create_restaurant(params["voucher"][:restaurant]) if restaurant.nil?

    @voucher = Voucher.new(voucher_params)
    @voucher[:restaurant_id] = restaurant.id
    @voucher[:user_id] = current_user.id

    respond_to do |format|
      if @voucher.save
        format.html { redirect_to @voucher, notice: 'Voucher was successfully created.' }
        format.json { render :show, status: :created, location: @voucher }
      else
        format.html { render :new }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vouchers/1
  # PATCH/PUT /vouchers/1.json
  def update
    respond_to do |format|
      if @voucher.update(voucher_params)
        format.html { redirect_to @voucher, notice: 'Voucher was successfully updated.' }
        format.json { render :show, status: :ok, location: @voucher }
      else
        format.html { render :edit }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vouchers/1
  # DELETE /vouchers/1.json
  def destroy
    @voucher.destroy
    respond_to do |format|
      format.html { redirect_to vouchers_url, notice: 'Voucher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def create_restaurant(params)
    split_params = params.split(",")
    clean_array = split_params.collect{|x| x.strip || x }
    name = clean_array[0]
    address = params
    city = clean_array[-2]
    country = clean_array[-1]
    restaurant = Restaurant.new(name: name, address: address, city: city, country: country)
    restaurant.save
    return restaurant
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_voucher
    @voucher = Voucher.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def voucher_params
    params.require(:voucher).permit(:name, :price, :notes, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <title>Buy Vouchers - Support Local Businesses</title>
    <meta name="description" content="Buy vouchers to support local businesses throughout Covid-19">

    <!-- Google / Search Engine Tags -->
    <meta itemprop="name" content="Voucher site - Buy vouchers">
    <meta itemprop="description" content="Support local businesses through Covid-19 by buying vouchers to redeem when they reopen.">
    <meta itemprop="image" content="https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=60.png">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://vouchersite.herokuapp.com/">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Buy vouchers to support local businesses throughout Covid-19">
    <meta property="og:description" content="Browse restaurants and vouchers and buy vouchers which you can redeem once they reopen. ">
    <meta property="og:image" content="https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=60.png">

    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Buy vouchers to support local businesses throughout Covid-19">
    <meta name="twitter:description" content="Browse restaurants and vouchers and buy vouchers which you can redeem once they reopen. ">
    <meta name="twitter:image" content="https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=60.png">

  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :city %>
    <%= f.input :neighbourhood %>
    <%= f.input :address %>
    <%= f.input :website %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container">
  <h1>Restaurants</h1>
  <% @restaurants.each_slice(2) do |(r1, r2)| %>
    <div class="row">
      <div class="col-xl-6"><%= render 'shared/restaurant_card', restaurant: r1 %></div>
      <div class="col-xl-6"><%= render 'shared/restaurant_card', restaurant: r2 if r2 %></div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="banner-restaurant" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@restaurant.photo.key, :width => 540, :height => 400, :crop => :fill) %>);">
  <div class="container">
    <h1><%=@restaurant.name %> Vouchers</h1>
    <p><%=@restaurant.tidy_address%></p>
  </div>
</div>

<% @restaurant.vouchers.each_slice(2) do |(v1, v2)| %>
  <div class="row">
    <div class="col-xl-6"><%= render 'shared/voucher_card', voucher: v1 %></div>
    <div class="col-xl-6"><%= render 'shared/voucher_card', voucher: v2 if v2 %></div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Add Voucher", new_voucher_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
         <%= link_to "Browse Restaurants", restaurants_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
         <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
        <!-- <li class="nav-item dropdown">
          <%# image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%# link_to "Action", "#", class: "dropdown-item" %>
            <%# link_to "Another action", "#", class: "dropdown-item" %>
            <%# link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li> -->
      <% else %>
        <li class="nav-item">
         <%= link_to "Browse Restaurants", restaurants_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
          <%= link_to "Own a business?", new_user_session_path, class: "dropdown-item" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_restaurant_card.html.erb
<div data-card="restaurant" data-id="<%=restaurant.id %>" class="clickable-card card-restaurant">
  <%= cl_image_tag(restaurant.photo.key, :width => 525, :height => 200, :crop => :fill) %>
  <div class="card-restaurant-infos">
    <div>
      <h2><%= restaurant.name %></h2>
      <p>
        <%= restaurant.tidy_address %>
      </p>
    </div>
    <h2>
      <%= link_to "Browse #{restaurant.vouchers.count} voucher#{restaurant.plural_vouchers}", restaurant_path(restaurant), type: "button", class: "btn btn-outline-secondary" %>
    </h2>
  </div>
</div>

app/views/shared/_voucher_card.html.erb
<div data-card="voucher" data-id="<%=voucher.id %>" class="clickable-card card-product">
  <%= cl_image_tag(voucher.photo.key, :width => 240, :height => 240) %>
  <div class="card-product-infos">
    <div>
      <h2>£<%= voucher.price %></h2>
      <p><%= voucher.notes %></p>
    </div>
    <div class="btn-container">
      <%= link_to "Buy", voucher, type: "button", class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/vouchers/_form.html.erb
<%= simple_form_for(@voucher) do |f| %>

  <div class="form-inputs">
    <%= f.input :restaurant %>
    <%= f.input :price %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vouchers/edit.html.erb
<h1>Editing Voucher</h1>

<%= render 'form', voucher: @voucher %>

<%= link_to 'Show', @voucher %> |
<%= link_to 'Back', vouchers_path %>

app/views/vouchers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vouchers</h1>

<% @vouchers.each do |voucher| %>
  <%= render 'shared/voucher_card', voucher: voucher %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>Name</th>
      <th>Price</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vouchers.each do |voucher| %>
      <tr>
        <td>£<%= voucher.price %></td>
        <td><%= voucher.notes %></td>
        <td><%= link_to 'Contact owner', voucher %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voucher', new_voucher_path %>

app/views/vouchers/new.html.erb
<h1>New Voucher</h1>
<%= render 'form', voucher: @voucher %>
<%= link_to 'Back', vouchers_path %>

app/views/vouchers/show.html.erb
<%= javascript_include_tag "https://www.paypal.com/sdk/js?client-id=#{ENV['PAYPAL_CLIENT_ID']}&currency=GBP" %>

<!-- <p id="notice"><%= notice %></p> -->

<div class="row">
  <div class="col-lg">
    <div class="banner-restaurant" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@voucher.photo.key, :width => 540, :height => 400, :crop => :fill) %>);">
      <div class="container">
        <h1><%=@voucher.restaurant.name %></h1>
        <p><%=@voucher.restaurant.tidy_address%></p>
      </div>
    </div>
  </div>
  <div class="col-lg  price-container">
    <div class="container">
      <h3>
        <strong>£<%= @voucher.price %></strong> - <%= @voucher.notes %>
      </h3>
      <div class="paypal-wrapper">
        <div id="paypal-button-container"></div>
      </div>
    </div>
  </div>
</div>

<%# link_to 'Back', vouchers_path %>
<script>
  paypal.Buttons({
    createOrder: function(data, actions) {
      // This function sets up the details of the transaction, including the amount and line item details.
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: <%= @voucher.price %>,
            currency: 'GBP'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      // This function captures the funds from the transaction.
      return actions.order.capture().then(function(details) {
        // This function shows a transaction success message to your buyer.
        alert('Transaction completed by ' + details.payer.name.given_name);
      });
    }
  }).render('#paypal-button-container');
  //This function displays Smart Payment Buttons on your web page.
</script>